upgrade thirdparty src, update configure/make files, fixes

diff --git a/cinelerra-4.6.mod/quicktime/configure b/cinelerra-4.6.mod/quicktime/configure
--- a/cinelerra-4.6.mod/quicktime/configure
+++ b/cinelerra-4.6.mod/quicktime/configure
@@ -10,15 +10,15 @@ if [ -x /usr/bin/nasm -o -x /usr/local/bin/nasm ]; then HAVE_NASM=y; else HAVE_N
 if [ -x /usr/bin/yasm -o -x /usr/local/bin/yasm ]; then HAVE_YASM=y; else HAVE_YASM=n; fi
 
 if [ `uname -m` = i686 ]; then
-	if [ $HAVE_NASM = n ]; then
-		echo " *** Nasm is required.  Download it from nasm.sourceforge.net"; 
-		ERROR=1
-	fi
+  if [ $HAVE_NASM = n ]; then
+    echo " *** Nasm is required.  Download it from nasm.sourceforge.net"; 
+    ERROR=1
+  fi
 fi
 
 if [ $HAVE_YASM = n ]; then
-	echo " *** Yasm is required.  Download it from www.tortall.net/projects/yasm/"; 
-	ERROR=1
+  echo " *** Yasm is required.  Download it from www.tortall.net/projects/yasm/"; 
+  ERROR=1
 fi
 
 # test for -msse support
@@ -27,7 +27,7 @@ rm -f a.out
 cat > conftest.c << EOF
 int main()
 {
-	return 0;
+  return 0;
 }
 EOF
 
@@ -38,15 +38,11 @@ if [ -x a.out ]; then HAVE_GCC=y; else HAVE_GCC=n; fi
 rm -f a.out conftest.c
 
 if [ $HAVE_GCC = n ]; then
-	echo " *** GCC 3.2.2 or greater is required.  Download it from gcc.gnu.org"; 
-	ERROR=1
+  echo " *** GCC 3.2.2 or greater is required.  Download it from gcc.gnu.org"; 
+  ERROR=1
 fi
 
-if [ $ERROR != 0 ]; then exit; fi
-
-if [ $? = 0 ]; then
-  echo "Configured successfully.  Type 'make' to build it.";
-else
-  echo "Error configuring thirdparty libraries."
+if [ $ERROR -ne 0 ]; then
+  exit 1
 fi
 
